///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1.Memrise.WebApp.EndEvents
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseBrowserOnDashboard recording.
    /// </summary>
    [TestModule("79b23647-3d2a-483c-bb5e-d282e2f99188", ModuleType.Recording, 1)]
    public partial class CloseBrowserOnDashboard : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1.MyTest1Repository repository.
        /// </summary>
        public static MyTest1.MyTest1Repository repo = MyTest1.MyTest1Repository.Instance;

        static CloseBrowserOnDashboard instance = new CloseBrowserOnDashboard();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseBrowserOnDashboard()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseBrowserOnDashboard Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'DoYouWantToLeaveThisSite'.", repo.DoYouWantToLeaveThisSite.SelfInfo, new RecordItemIndex(0));
            //Host.Current.CloseApplication(repo.DoYouWantToLeaveThisSite.Self, new Duration(0));
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardMemriseGoogleChrome.Close' at 2;1.", repo.DashboardMemriseGoogleChrome.CloseInfo, new RecordItemIndex(1));
            //repo.DashboardMemriseGoogleChrome.Close.Click("2;1");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'DashboardMemriseGoogleChrome'.", repo.DashboardMemriseGoogleChrome.SelfInfo, new RecordItemIndex(2));
            Host.Current.CloseApplication(repo.DashboardMemriseGoogleChrome.Self, new Duration(0));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
