///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1.Memrise.AndroidApp.Logins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EmailLogin recording.
    /// </summary>
    [TestModule("3827aa83-5c87-4809-a30e-d7ad07188b2a", ModuleType.Recording, 1)]
    public partial class EmailLogin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1.MyTest1Repository repository.
        /// </summary>
        public static MyTest1.MyTest1Repository repo = MyTest1.MyTest1Repository.Instance;

        static EmailLogin instance = new EmailLogin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EmailLogin()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EmailLogin Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'io.selendroid.testapp' on device " + Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName() + ".", new RecordItemIndex(0));
            Host.Local.RunMobileApp(Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName(), "io.selendroid.testapp", true);
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.InputAddsCheckBox' at Center", repo.IoSelendroidTestapp.InputAddsCheckBoxInfo, new RecordItemIndex(1));
            repo.IoSelendroidTestapp.InputAddsCheckBox.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.InputAddsCheckBox' at Center", repo.IoSelendroidTestapp.InputAddsCheckBoxInfo, new RecordItemIndex(2));
            repo.IoSelendroidTestapp.InputAddsCheckBox.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Linear.ShowToastButton' at Center", repo.IoSelendroidTestapp.Linear.ShowToastButtonInfo, new RecordItemIndex(3));
            repo.IoSelendroidTestapp.Linear.ShowToastButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Linear.ShowPopupWindowButton' at Center", repo.IoSelendroidTestapp.Linear.ShowPopupWindowButtonInfo, new RecordItemIndex(4));
            repo.IoSelendroidTestapp.Linear.ShowPopupWindowButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.PopupDismissButton' at Center", repo.IoSelendroidTestapp.PopupDismissButtonInfo, new RecordItemIndex(5));
            repo.IoSelendroidTestapp.PopupDismissButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.MyTextField' at Center", repo.IoSelendroidTestapp.MyTextFieldInfo, new RecordItemIndex(6));
            repo.IoSelendroidTestapp.MyTextField.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'cookies' on item 'IoSelendroidTestapp.MyTextField'.", repo.IoSelendroidTestapp.MyTextFieldInfo, new RecordItemIndex(7));
            repo.IoSelendroidTestapp.MyTextField.Element.SetAttributeValue("Text", "cookies");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
