///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1.Memrise.AndroidApp.Logins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("a6d522c6-f45a-4006-b52b-6995bfb04845", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1.MyTest1Repository repository.
        /// </summary>
        public static MyTest1.MyTest1Repository repo = MyTest1.MyTest1Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            Username = "beatrisy";
            Password = "MemriseBM12345";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _Username;

        /// <summary>
        /// Gets or sets the value of variable Username.
        /// </summary>
        [TestVariable("cc81f46a-60d1-4c9a-a78a-6c58e29369f4")]
        public string Username
        {
            get { return _Username; }
            set { _Username = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("9538eb25-ccbf-49a2-a307-50a37d1fbeee")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.memrise.android.memrisecompanion' on device " + Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName() + ".", new RecordItemIndex(0));
            Host.Local.RunMobileApp(Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName(), "com.memrise.android.memrisecompanion", true);
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.LanguagePlanetLogIn' at 229;90", repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.LanguagePlanetLogInInfo, new RecordItemIndex(1));
            repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.LanguagePlanetLogIn.Touch("229;90");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingEmailField' at 834;111", repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingEmailFieldInfo, new RecordItemIndex(2));
            repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingEmailField.Touch("834;111");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Username' on item 'ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingEmailField'.", repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingEmailFieldInfo, new RecordItemIndex(3));
            repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingEmailField.Element.SetAttributeValue("Text", Username);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingPasswordField' at 797;91", repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingPasswordFieldInfo, new RecordItemIndex(4));
            repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingPasswordField.Touch("797;91");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Password' on item 'ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingPasswordField'.", repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingPasswordFieldInfo, new RecordItemIndex(5));
            repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.OnboardingPasswordField.Element.SetAttributeValue("Text", Password);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.Frame' at Center", repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.FrameInfo, new RecordItemIndex(6));
            repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.Frame.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.FlagView' at 24;-787", repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.FlagViewInfo, new RecordItemIndex(7));
            repo.ComMemriseAndroidMemrisecompanion.LanguageSelectionActivity.FlagView.Touch("24;-787");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComMemriseAndroidMemrisecompanion.Linear.BottomNavigationItemTitle' at 123;42", repo.ComMemriseAndroidMemrisecompanion.Linear.BottomNavigationItemTitleInfo, new RecordItemIndex(8));
            repo.ComMemriseAndroidMemrisecompanion.Linear.BottomNavigationItemTitle.Touch("123;42");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComMemriseAndroidMemrisecompanion.Linear.BottomNavigationNotification' at 1;19", repo.ComMemriseAndroidMemrisecompanion.Linear.BottomNavigationNotificationInfo, new RecordItemIndex(9));
            repo.ComMemriseAndroidMemrisecompanion.Linear.BottomNavigationNotification.Touch("1;19");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComMemriseAndroidMemrisecompanion.Linear.BottomNavigationItemIcon' at 70;57", repo.ComMemriseAndroidMemrisecompanion.Linear.BottomNavigationItemIconInfo, new RecordItemIndex(10));
            repo.ComMemriseAndroidMemrisecompanion.Linear.BottomNavigationItemIcon.Touch("70;57");
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
