///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1.Memrise.WebApp.Dashboard
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The HomeNavigation recording.
    /// </summary>
    [TestModule("70a6b8ad-a51b-4f31-95ff-1511d8b3d316", ModuleType.Recording, 1)]
    public partial class HomeNavigation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1.MyTest1Repository repository.
        /// </summary>
        public static MyTest1.MyTest1Repository repo = MyTest1.MyTest1Repository.Instance;

        static HomeNavigation instance = new HomeNavigation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public HomeNavigation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static HomeNavigation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.HeaderNav.Home' at 20;14.", repo.MemriseLearningMadeJoyful.HeaderNav.HomeInfo, new RecordItemIndex(0));
            repo.MemriseLearningMadeJoyful.HeaderNav.Home.Click("20;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MemriseLearningMadeJoyful.HeaderNav.HttpsWwwMemriseComPremiumSourceEq' at 47;29.", repo.MemriseLearningMadeJoyful.HeaderNav.HttpsWwwMemriseComPremiumSourceEqInfo, new RecordItemIndex(1));
            repo.MemriseLearningMadeJoyful.HeaderNav.HttpsWwwMemriseComPremiumSourceEq.MoveTo("47;29");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -3720 units.", new RecordItemIndex(2));
            Mouse.ScrollWheel(-3720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.HeaderNav.Home' at 36;15.", repo.MemriseLearningMadeJoyful.HeaderNav.HomeInfo, new RecordItemIndex(3));
            repo.MemriseLearningMadeJoyful.HeaderNav.Home.Click("36;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Content.BeatriceTest' at 68;13.", repo.MemriseLearningMadeJoyful.Content.BeatriceTestInfo, new RecordItemIndex(4));
            repo.MemriseLearningMadeJoyful.Content.BeatriceTest.Click("68;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Beatrice test') on item 'MemriseLearningMadeJoyful.BeatriceTest'.", repo.MemriseLearningMadeJoyful.BeatriceTestInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.MemriseLearningMadeJoyful.BeatriceTestInfo, "InnerText", "Beatrice test");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=0,Y=0}.", new RecordItemIndex(6));
            Mouse.MoveTo(0, 0);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
