///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1.Memrise.WebApp.Staging
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Payment recording.
    /// </summary>
    [TestModule("1765bd43-0044-43ba-81a9-74ab7548b394", ModuleType.Recording, 1)]
    public partial class Payment : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1.MyTest1Repository repository.
        /// </summary>
        public static MyTest1.MyTest1Repository repo = MyTest1.MyTest1Repository.Instance;

        static Payment instance = new Payment();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Payment()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Payment Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://staging.memrise.com/login' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://staging.memrise.com/login", "chrome", "", false, false, false, true, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLogin.Text' at 8;14.", repo.MemriseLogin.TextInfo, new RecordItemIndex(1));
            repo.MemriseLogin.Text.Click("8;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hello Memrise' with focus on 'MemriseLogin.Text'.", repo.MemriseLogin.TextInfo, new RecordItemIndex(2));
            repo.MemriseLogin.Text.PressKeys("Hello Memrise");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLogin.Ccnum' at 38;25.", repo.MemriseLogin.CcnumInfo, new RecordItemIndex(3));
            repo.MemriseLogin.Ccnum.Click("38;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '4242424242424242' with focus on 'MemriseLogin.Ccnum'.", repo.MemriseLogin.CcnumInfo, new RecordItemIndex(4));
            repo.MemriseLogin.Ccnum.PressKeys("4242424242424242");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLogin.Text1' at 73;15.", repo.MemriseLogin.Text1Info, new RecordItemIndex(5));
            repo.MemriseLogin.Text1.Click("73;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123' with focus on 'MemriseLogin.Text1'.", repo.MemriseLogin.Text1Info, new RecordItemIndex(6));
            repo.MemriseLogin.Text1.PressKeys("123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLogin.PayBtn' at 56;8.", repo.MemriseLogin.PayBtnInfo, new RecordItemIndex(7));
            repo.MemriseLogin.PayBtn.Click("56;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MemriseLogin.CongratulationsUpgradeSuccessful'.", repo.MemriseLogin.CongratulationsUpgradeSuccessfulInfo, new RecordItemIndex(8));
            Validate.Exists(repo.MemriseLogin.CongratulationsUpgradeSuccessfulInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLogin.Continue' at 252;18.", repo.MemriseLogin.ContinueInfo, new RecordItemIndex(9));
            repo.MemriseLogin.Continue.Click("252;18");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
