///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1.Memrise.WebApp.Payment
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PromoPopUpAccept recording.
    /// </summary>
    [TestModule("44c2302d-3958-411f-b75f-89dbc70bd311", ModuleType.Recording, 1)]
    public partial class PromoPopUpAccept : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1.MyTest1Repository repository.
        /// </summary>
        public static MyTest1.MyTest1Repository repo = MyTest1.MyTest1Repository.Instance;

        static PromoPopUpAccept instance = new PromoPopUpAccept();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PromoPopUpAccept()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PromoPopUpAccept Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'MemriseLearningMadeJoyful.ModalBody'.", repo.MemriseLearningMadeJoyful.ModalBodyInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.MemriseLearningMadeJoyful.ModalBodyInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.PTag50PercentOFF' at 50;26.", repo.MemriseLearningMadeJoyful.PTag50PercentOFFInfo, new RecordItemIndex(1));
            repo.MemriseLearningMadeJoyful.PTag50PercentOFF.Click("50;26");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
