///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1.Memrise.WebApp.Lessons
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartinASession recording.
    /// </summary>
    [TestModule("58d877e0-4d18-4101-960d-4c894965b86a", ModuleType.Recording, 1)]
    public partial class StartinASession : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1.MyTest1Repository repository.
        /// </summary>
        public static MyTest1.MyTest1Repository repo = MyTest1.MyTest1Repository.Instance;

        static StartinASession instance = new StartinASession();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartinASession()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartinASession Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Content.Learn' at 21;8.", repo.MemriseLearningMadeJoyful.Content.LearnInfo, new RecordItemIndex(0));
            repo.MemriseLearningMadeJoyful.Content.Learn.Click("21;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Boxes.NextIcon' at 15;25.", repo.MemriseLearningMadeJoyful.Boxes.NextIconInfo, new RecordItemIndex(1));
            repo.MemriseLearningMadeJoyful.Boxes.NextIcon.Click("15;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Boxes.NextIcon' at 13;31.", repo.MemriseLearningMadeJoyful.Boxes.NextIconInfo, new RecordItemIndex(3));
            repo.MemriseLearningMadeJoyful.Boxes.NextIcon.Click("13;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Boxes.Hallo' at 29;24.", repo.MemriseLearningMadeJoyful.Boxes.HalloInfo, new RecordItemIndex(5));
            repo.MemriseLearningMadeJoyful.Boxes.Hallo.Click("29;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Boxes.WasGehtAb' at 76;26.", repo.MemriseLearningMadeJoyful.Boxes.WasGehtAbInfo, new RecordItemIndex(7));
            repo.MemriseLearningMadeJoyful.Boxes.WasGehtAb.Click("76;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(8));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Boxes.NextIcon' at 25;28.", repo.MemriseLearningMadeJoyful.Boxes.NextIconInfo, new RecordItemIndex(9));
            repo.MemriseLearningMadeJoyful.Boxes.NextIcon.Click("25;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(10));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Boxes.NextIcon' at 24;28.", repo.MemriseLearningMadeJoyful.Boxes.NextIconInfo, new RecordItemIndex(11));
            repo.MemriseLearningMadeJoyful.Boxes.NextIcon.Click("24;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(12));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Boxes.SpanTagHi' at 17;20.", repo.MemriseLearningMadeJoyful.Boxes.SpanTagHiInfo, new RecordItemIndex(13));
            repo.MemriseLearningMadeJoyful.Boxes.SpanTagHi.Click("17;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(14));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.Boxes.WasGehtAb' at 107;16.", repo.MemriseLearningMadeJoyful.Boxes.WasGehtAbInfo, new RecordItemIndex(15));
            repo.MemriseLearningMadeJoyful.Boxes.WasGehtAb.Click("107;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(16));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemriseLearningMadeJoyful.HttpsWwwMemriseComHome' at 11;6.", repo.MemriseLearningMadeJoyful.HttpsWwwMemriseComHomeInfo, new RecordItemIndex(17));
            repo.MemriseLearningMadeJoyful.HttpsWwwMemriseComHome.Click("11;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(18));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DoYouWantToLeaveThisSite.Leave' at 34;8.", repo.DoYouWantToLeaveThisSite.LeaveInfo, new RecordItemIndex(19));
            repo.DoYouWantToLeaveThisSite.Leave.Click("34;8");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
